---
format: pdf
editor: visual
---

```{r, include= FALSE}
library(tibble)
library(tidyverse)
#library(rstanarm)
```


```{r}
set.seed(301)
generate_data <- function(i = 1000) {
  data <- tibble(
    party = sample(c("yes", "no"), i, replace = TRUE),
    age = sample(c("18-24", "25-34", "35-44", "45-54", "55-64", "65+"), i, replace = TRUE),
    gender = sample(c("male", "female"), i, replace = TRUE),
    income = sample(c("<$25K", "$25K-$50K", "$50K-$75K", "$75K-$100K", ">$100K"), i, replace = TRUE),
    education = sample(c("high school", "bachelor's degree", "master's degree", "PhD"), i, replace = TRUE))
   return(data)
}
sim_data <- generate_data(1000)
sim_data

```


```{r, fig.width=8, fig.height= 3}
#| echo: false

set.seed(302)
sim_data <- generate_data(1000)
sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false

set.seed(303)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false

set.seed(304)
sim_data <- generate_data(1000)

sim_data
```


```{r, fig.height= 3, fig.width=8}
#| echo: false

set.seed(305)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false


set.seed(306)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height=3, fig.width=8}
#| echo: false


set.seed(307)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false


set.seed(308)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false


set.seed(309)
sim_data <- generate_data(1000)

sim_data
```

```{r, fig.height= 3, fig.width=8}
#| echo: false


set.seed(300)
sim_data <- generate_data(1000)

sim_data
```
