---
title: "quiz 8 plot"
format: pdf
editor: visual
---
```{r, include= FALSE}
library(tibble)
library(tidyverse)
#library(rstanarm)
```

```{r, fig.width=8, fig.height= 3}
set.seed(301)
generate_data <- function(i = 1000) {
  data <- tibble(
    party = sample(c("yes", "no"), i, replace = TRUE),
    age = sample(c("18-24", "25-34", "35-44", "45-54", "55-64", "65+"), i, replace = TRUE),
    gender = sample(c("male", "female"), i, replace = TRUE),
    income = sample(c("<$25K", "$25K-$50K", "$50K-$75K", "$75K-$100K", ">$100K"), i, replace = TRUE),
    education = sample(c("high school", "bachelor's degree", "master's degree", "PhD"), i, replace = TRUE))
   return(data)
}
sim_data <- generate_data(1000)

ggplot(sim_data, aes(x=age, fill=party)) +
  geom_bar(position="dodge") +
  facet_grid(~income) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x="Age", y="Count", fill="Party")

#model <- stan_glm(party ~ age + gender + income + education, data = sim_data, family = binomial(link = "logit"))
```
